export const CSS = {
  menu: "menu",
  logo: "logo",
  esriLogo: "esri-logo-app",
  icon: "icon",
  menuItem: "menu-item",
  measure: "measure",
  compare: "compare",
  share: "share",
  location: "location",
  wrapper: "wrapper",
  abovePage: "above-page",
  belowPage: "below-page",
  label: "label",
  logoTop: "logo-top",
  logoBottom: "logo-bottom",
  menuBackground: "menu-background",
  border: "page-border",
  closeButton: "close-button",
  esriWidget: "esri-widget",

  submenuItem: "submenu-item",
  submenuContainer: "submenu-container",
  lineMeasure: "line-measure",
  areaMeasure: "area-measure",
  elevationMeasure: "elevation-measure",
  pageContainer: "page-container",
  loadingPage: "loading-page",
};
